eng_prp_first = set(['i', 'me', 'mine', 'myself',
    'we', 'us', 'ours', 'ourselves'])
eng_prp_second = set(['you', 'your', 'yours', 'yourself', 'yourselves'])
eng_prp_third = set(['he', 'him', 'his', 'himself', 'she', 'her', 'his', 'herself', 'they', 'them', 'themself', 'themselves'])
eng_punc = set(['!', '.', '?'])

# Hate speech lexicon from https://github.com/t-davidson/hate-speech-and-offensive-language/tree/master/lexicons

#TODO turn these into regexes cause they don't work now.
eng_hate = {
     'a bitch made',
     'a bitch made nigga',
     'a dirty',
     'a fag and',
     'a fag but',
     'a faggot and',
     'a faggot for',
     'a fucking queer',
     'a lame nigga you',
     'a nigga ask',
     'a nigger',
     'a white person',
     'a white trash',
     'all niggers',
     'all these fucking',
     'all white',
     'allah akbar',
     'always fuck',
     'are all white',
     'ass white',
     'be killed',
     'be killed for',
     'beat him',
     'biggest faggot',
     'bitch made nigga',
     'blacks',
     'blame the',
     'butt ugly',
     'chink',
     'chink eyed',
     'chinks',
     'chinks in',
     'coon shit',
     'dumb monkey',
     'dumb nigger',
     'dykes',
     'fag and',
     'fag but',
     'faggot',
     'faggot a',
     'faggot and',
     'faggot ass',
     'faggot bitch',
     'faggot for',
     'faggot if you ever',
     'faggot smh',
     'faggot that',
     'faggots',
     'faggots and',
     'faggots like',
     'faggots like you',
     'faggots usually',
     'faggots usually have',
     'faggots who',
     'fags',
     'fags are',
     'fuck outta here',
     'fuck u talking',
     'fuck you too',
     'fuckin faggot',
     'fucking faggot',
     'fucking gay',
     'fucking hate',
     'fucking hate you',
     'fucking nigger',
     'fucking queer',
     'full of white',
     'full of white trash',
     'gay ass',
     'get raped',
     'hate all',
     'hate faggots',
     'hate fat',
     'hate you',
     'here faggot',
     'him a nigga',
     'his shorty bitch',
     'homo',
     'how many niggers',
     'how many niggers are',
     'inbred',
     'is a fag',
     'is a faggot',
     'is a fuckin',
     'is a fucking',
     'is a nigger',
     'is full of white',
     'is white',
     'jungle bunny',
     'kill all',
     'kill yourself',
     'lame nigga you a',
     'like a faggot',
     'like da colored',
     'little faggot',
     'many niggers',
     'many niggers are',
     'many niggers are in',
     'married to',
     'me faggot',
     'my coon',
     'nigga and his',
     'nigga ask',
     'nigga you a lame',
     'niggas like',
     'nigger',
     'nigger ass',
     'nigger is',
     'nigger music',
     'niggers',
     'niggers are',
     'niggers are in',
     'niggers are in my',
     'of fags',
     'of white',
     'of white trash',
     'queers',
     'raped',
     'raped and',
     'raped by',
     'sand nigger',
     'savages',
     'savages that',
     'shorty bitch',
     'shut up nigger',
     'slave',
     'spear chucker',
     'spic',
     'spic cop',
     'still a faggot',
     'stupid nigger',
     'that fag',
     'that faggot',
     'that nigger',
     'the biggest faggot',
     'the faggots',
     'the faggots who',
     'the female',
     'the fuck do',
     'the niggers',
     'their heads',
     'them white',
     'then faggot',
     'they all look',
     'this nigger',
     'to rape',
     'trailer park',
     'trash with',
     'u fuckin',
     'ugly dyke',
     'up nigger',
     'wetback',
     'wetbacks',
     'what a fag',
     'white ass',
     'white bitch in',
     'white boy',
     'white person',
     'white trash',
     'white trash and',
     'whites',
     'wit a lame nigga',
     'with niggas',
     'you a fag',
     'you a lame',
     'you a lame bitch',
     'you a nigger',
     'you fag',
     'you fuck wit',
     'you fuck wit a',
     'you fucking faggot',
     'you nigger',
     'you niggers',
     'your a cunt',
     'your a dirty',
     'your bitch in',
     'your faggot',
     'your nigger'
 }


eng_hedge = {
     'almost',
     'apparent',
     'apparently',
     'appear',
     'appeared',
     'appears',
     'approximately',
     'argue',
     'argued',
     'argues',
     'around',
     'assume',
     'assumed',
     'broadly',
     'certain amount',
     'certain extent',
     'certain level',
     'claim',
     'claimed',
     'claims',
     'doubt',
     'doubtful',
     'essentially',
     'estimate',
     'estimated',
     'fairly',
     'feel',
     'feels',
     'felt',
     'frequently',
     'from my perspective',
     'from our perspective',
     'from this perspective',
     'generally',
     'guess',
     'in general',
     'in most cases',
     'in most instances',
     'in my opinion',
     'in my view',
     'in our opinion',
     'in our view',
     'in this view',
     'indicate',
     'indicated',
     'indicates',
     'largely',
     'likely',
     'mainly',
     'may',
     'maybe',
     'might',
     'mostly',
     'often',
     'on the whole',
     'ought',
     'perhaps',
     'plausible',
     'plausibly',
     'possible',
     'possibly',
     'postulate',
     'postulated',
     'postulates',
     'presumable',
     'presumably',
     'probable',
     'probably',
     'quite',
     'rather',
     'relatively',
     'roughly',
     'seems',
     'should',
     'sometimes',
     'somewhat',
     'suggest',
     'suggested',
     'suggests',
     'suppose',
     'supposed',
     'supposes',
     'suspect',
     'suspects',
     'tend to',
     'tended to',
     'tends to',
     'think',
     'thinking',
     'thought',
     'to my knowledge',
     'typical',
     'typically',
     'uncertain',
     'uncertainly',
     'unclear',
     'unclearly',
     'unlikely',
     'usually'
 }
